theme: jekyll-theme-leap-day
<<<<<<< HEAD

title: Phys 241
=======
title: Phys241
description: Physical modeling for New Mexico Tech Physics 241
>>>>>>> 5de6c6d79d425081596d1109259db2324651d1c9
repository: pharaohcola13/Phys241
